Добавлена функция-сумматор
js-tasks-ru/jsbasic-20201022_ellan pull request #1
Opened 2020-10-19 11:20 UTC by Den0702

2020-10-19 11:28 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-10-22 11:20 UTC, koalex requested changes
После того как исправишь замечание добавь меня заново в ревью!

2020-10-22 11:20 UTC, koalex commented on 0-module/1-task/index.js
> +sum(2, 5);
удали строку 10

2020-10-22 16:16 UTC, Den0702 commented on 0-module/1-task/index.js
> +sum(2, 5);
понял

2020-10-22 17:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-25 06:51 UTC, koalex approved these changes

2020-10-25 06:51 UTC, merged