Factorial
js-tasks-ru/jsbasic-20201022_ellan pull request #2
Opened 2020-10-29 09:41 UTC by Den0702

2020-10-29 10:16 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 0 равен 1
+ факториал 5 равен 120 
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-10-29 10:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-29 11:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 3 равен 6 
+ факториал 1 равен 1
+ факториал 0 равен 1
```
```diff
Допишите функцию валидации имени пользователя
- если имя корректное, то true
- если содержит пробелы, то false
- если меньше 4 символов то false
```

2020-10-29 12:46 UTC, koalex approved these changes

2020-10-29 12:46 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-29 12:49 UTC, koalex requested changes
нужно решить 1-module-2-task чтобы прошёл PR

2020-10-29 12:49 UTC, koalex commented on 1-module/1-task/index.js
> +factorial(5);
строку 14 надо удалить

2020-10-29 13:43 UTC, Den0702 commented on 1-module/1-task/index.js
> +factorial(5);
@koalex в этом 1f65982  коммите я удалил

2020-10-29 14:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-29 14:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-29 15:00 UTC, Den0702 commented on 1-module/1-task/index.js
> +factorial(5);
@koalex задача с первой заглавной у меня работает - я проверял в ручную 'вася', 'в' и ' ' -> 'Вася', 'в' и ' '. Но тесты не проходит

2020-10-29 15:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 0 равен 1
+ факториал 5 равен 120 
+ факториал 3 равен 6 
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
+ должна делать первый символ заглавным
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если содержит пробелы, то false
+ если имя корректное, то true
```
```diff
Проверка на спам
- должна возвращать false для 'innocent rabbit'
- должна возвращать true для 'free xxxxx'
- должна возвращать true для '1XbeT now'
```

2020-10-30 08:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-30 11:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-31 15:38 UTC, koalex approved these changes

2020-10-31 15:38 UTC, merged